/*
 * generated by Xtext
 */
package org.johnf;

import org.eclipse.xtext.linking.ILinker;
import org.johnf.linker.MyDslLazyLinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.johnf.AbstractMyDslRuntimeModule {

	@Override
	public Class<? extends ILinker> bindILinker() {
		// Add Built-in Types to model before linking.
		return MyDslLazyLinker.class;
	}
}
