/*
 * generated by Xtext
 */
package org.johnf.mydsl1;

import org.eclipse.xtext.linking.ILinker;
import org.johnf.mydsl1.linker.MyDslLazyLinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.johnf.mydsl1.AbstractMyDslRuntimeModule {
	@Override
	public Class<? extends ILinker> bindILinker() {
		// Add Built-in Types to model before linking.
		return MyDslLazyLinker.class;
	}
}
